# Generated by Django 4.2.23 on 2025-06-21 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=datetime.datetime.now)),
                ('reviewed', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='menu.menu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='menu.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='accounts.profile')),
            ],
        ),
    ]
