# Generated by Django 4.2.23 on 2025-06-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_store_number_store_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
