# Generated by Django 4.2.23 on 2025-06-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_store_image'),
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricegrain',
            name='review_id',
        ),
        migrations.AddField(
            model_name='riceball',
            name='point',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='ricegrain',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.review'),
        ),
        migrations.AddField(
            model_name='ricemap',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
